apt_cache_valid_time: 3600
php_max_execution_time: 700
upload_max_filesize : 300M
upload_max_size: 300M
php_upload_max_filesize: 300M
php_post_max_size: 300M
apt_package_state: present
apt_security_package_state: latest
apt_dev_package_state: latest
composer_keep_updated: true
php_version: "8.2"
ntp_timezone: Etc/UTC
ntp_manage_config: true
max_journal_size: 512M
www_root: /srv/www
letsencrypt_contact_emails:
  - dsemblano@gmail.com

# Values of raw_vars will be wrapped in `{% raw %}` to avoid templating problems if values include `{%` and `{{`.
# Will recurse dicts/lists. `*` is wildcard for one or more dict keys, list indices, or strings. Example:
#   - vault_wordpress_sites.*.*_salt    -- matches vault_wordpress_sites.example.com.env.secure_auth_salt etc.
# Will not function for var names or topmost dict keys that contain a period ('.').
raw_vars:
  - vault_mail_password
  - vault_mysql_root_password
  - vault_users.*.password
  - vault_users.*.salt
  - vault_wordpress_env_defaults
  - vault_wordpress_sites
