# Created by trellis-cli v1.7.0
# Documentation: https://docs.roots.io/trellis/master/vault/

vault_mysql_root_password: ln5Hu4MF7i5Nag51uQDw8AXGRChz3ZgCxn2seJtI6Y7bzkcswlHmqSVDHRX5P4fn
vault_users:
- name: '{{ admin_user }}'
  password: WenARoS2RBljr5pW5ArlCHkb3QjhX1VKz8wdhQ0RSjxeeGmtNuOWnvOZcQ67gUYX
  salt: FyC3OjGcZV2Y561Ax0RMTAOsMxgSCfJmzxBYTUSBRYtrijzerXcdtizpUlKwinox
vault_wordpress_sites:
  tijolocwb.com.br:
    admin_password: Fd3UYNbKTsB2JLhOZHd42xbcTumtvjXAIrzbmdEaHbj9SWb4sNNHNHfeJ3FaN4U6
    env:
      db_password: BR4wyiHsMMkqID7uVsDe8PjCHCIyh2NgU3jl7Oc7uGPzWNxzWHSo89zeFYRvkWW8
      auth_key: nOrTKphNEyfGM2ktWrqetaWGVaesYi9MgIKZtVBBlgberWtf2F6NyGadrJHwOoQp
      secure_auth_key: Xo2ZnvyJCQcvbUwVXMbZfwH9UaFigeyclMibfxRY14qYGWwgfSHIRbsRXQ4hMgdo
      logged_in_key: GzvDoNHCBDImeMX8dH1aqZ55ZQQmMCHRDhPzFixOgvjFcz35RyqGPDVTzPTQbPkP
      nonce_key: YJ3GxYT6JKwKpT1f2ZGXaQ5H8b1RHb3PfeXCitgkfsOHBnl13EDYmNPUUZyOwc87
      auth_salt: rONzVO9XmAmxlEZPyhhGNNtyuKrqcSkpFDos0s9bBBdfjdysr6z2tD1PMDLXNRa9
      secure_auth_salt: 7qtvGHx6CjM3WCiD0Gq4F0yIUicoMz3Os3pkMJKuIHe2imtqcvDJpLlhZYtfm6XR
      logged_in_salt: pEDtdjWtKcMEDdXAojjZax4K8XpaiEf1aZ0drhESRgdISChHRxSUkRIBMHrRrJUp
      nonce_salt: CDK8nvg6pgkpMfJGvjIbedCpNPjmRLIq5MTuFgJEMjooHBFwaE6bHwHNCf97muiX
